#title: Eunjong Choi1
#url: "https://eunjong-choi.github.io/"
#baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

nav:
 - name: "About"	
   link: "/index"
 - name: "publications"
   link: "/publications"
 - name: "Servies"
   link: "/servies"
 - name: "Miscellaneous"
   link: "/miscellaneous"


sass:
    style: compressed
    sass_dir: _sass
