title: Eunjong Choi
url: "https://eunjong-choi.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

nav:
 - name: "About"
   link: "/about_me"
 - name: "publications"
   link: "/publications"
 - name: "Servies"
   link: "/servies"


sass:
    style: compressed
    sass_dir: _sass
