title: Eunjong Choi
url: "https://eunjong-choi.github.io/"
baseurl: "/about_me"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about_me/"
 - name: "publications"
   link: "resume.pdf"
 - name: "Servies"
   link: "servies"
